"""THX-style virtual surround for the headset, via a PipeWire HRTF convolver.

This is NOT real Windows THX Spatial Audio — that's a licensed Windows-only
DSP. What this gets instead is a comparable binaural/HRTF virtual-surround
effect using PipeWire's stock filter-chain convolver plus a HeSuVi-format
impulse-response (IR) file — the same mechanism third-party tools like
IrateGoose (github.com/Barafu/IrateGoose) use. See THX_SETUP.md in the repo
root for where to get an IR file and how this fits together.

`components_installed()` gates everything else: if the IR file isn't
present, none of the functions below touch PipeWire or the device.
"""

import os
import subprocess
import time

IR_FILE   = os.path.expanduser('~/.local/share/lynapse/thx/razer.wav')
CONF_PATH = os.path.expanduser('~/.config/pipewire/pipewire.conf.d/60-lynapse-thx.conf')
SINK_NAME = 'effect_input.lynapse-thx'

# Proper 2-channel-in binaural convolver — NOT the usual 8-channel-in HeSuVi
# graph. The headset's game sink is hard-locked to stereo (confirmed via
# `pactl`), so an 8-channel-in graph leaves 6 of 8 inputs permanently silent
# (PipeWire's default upmix just maps L->FL/R->FR and synthesizes nothing
# else) — the per-channel IR levels are balanced assuming all 8 contribute,
# so only 2 landing means quiet, thin output. Real Windows THX does its own
# stereo->7.1.4 upmix before the HRTF stage; we don't have that, so instead
# we skip needing it entirely: convolve L/R straight through the file's
# front-left/front-right HRIR pair (both the direct and cross-ear response
# for each), which is a standard binaural stereo-widening technique and
# gives a correctly-leveled result since nothing here depends on channels
# that were never going to carry a signal.
_CONF_TEMPLATE = '''# Auto-generated by Lynapse — regenerated each time THX is turned on.
# 2-channel binaural convolver sink (HRTF stereo widening via PipeWire
# filter-chain). See THX_SETUP.md in the Lynapse repo for background.

context.modules = [
    { name = libpipewire-module-filter-chain
        flags = [ nofail ]
        args = {
            node.description = "Lynapse THX Surround"
            media.name       = "Lynapse THX Surround"
            filter.graph = {
                nodes = [
                    { type = builtin label = copy name = copyL }
                    { type = builtin label = copy name = copyR }

                    # front-left HRIR pair (this ear + cross ear)
                    { type = builtin label = convolver name = convL_L config = { filename = "__IR_FILE__" channel = 0 } }
                    { type = builtin label = convolver name = convL_R config = { filename = "__IR_FILE__" channel = 1 } }
                    # front-right HRIR pair (cross ear + this ear)
                    { type = builtin label = convolver name = convR_R config = { filename = "__IR_FILE__" channel = 7 } }
                    { type = builtin label = convolver name = convR_L config = { filename = "__IR_FILE__" channel = 8 } }

                    { type = builtin label = mixer name = mixL }
                    { type = builtin label = mixer name = mixR }
                ]
                links = [
                    { output = "copyL:Out" input = "convL_L:In" }
                    { output = "copyL:Out" input = "convL_R:In" }
                    { output = "copyR:Out" input = "convR_R:In" }
                    { output = "copyR:Out" input = "convR_L:In" }

                    { output = "convL_L:Out" input = "mixL:In 1" }
                    { output = "convR_L:Out" input = "mixL:In 2" }
                    { output = "convL_R:Out" input = "mixR:In 1" }
                    { output = "convR_R:Out" input = "mixR:In 2" }
                ]
                inputs  = [ "copyL:In" "copyR:In" ]
                outputs = [ "mixL:Out" "mixR:Out" ]
            }
            capture.props = {
                node.name      = "effect_input.lynapse-thx"
                media.class    = Audio/Sink
                audio.channels = 2
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name      = "effect_output.lynapse-thx"
                node.passive   = true
                audio.channels = 2
                audio.position = [ FL FR ]
                target.object  = "__TARGET__"
            }
        }
    }
]
'''


def components_installed():
    """Whether the HRIR file this feature needs is present."""
    try:
        return os.path.getsize(IR_FILE) > 0
    except OSError:
        return False


def _pactl(*args, timeout=5):
    try:
        r = subprocess.run(['pactl', *args], capture_output=True, text=True, timeout=timeout)
        return r.returncode == 0, r.stdout, r.stderr
    except Exception as e:
        return False, '', str(e)


def _sinks():
    """[(id, name, state), ...] from `pactl list sinks short`."""
    ok, out, _ = _pactl('list', 'sinks', 'short')
    if not ok:
        return []
    result = []
    for line in out.splitlines():
        f = line.split('\t')
        if len(f) >= 5:
            result.append((f[0], f[1], f[4]))
    return result


def _find_game_sink():
    """(id, name) for the connected BlackShark's *game* audio sink
    specifically. THX/surround should only ever touch game/media audio —
    never chat/voice-call audio, so a Discord call etc. is left completely
    alone, matching how THX Spatial Audio behaves in Windows Synapse (it's
    scoped to the game channel there too). Falls back to any BlackShark sink
    if the device doesn't expose a separate game/chat split (e.g. a wired
    variant without game_chat_balance). None if no BlackShark sink at all."""
    matches = [s for s in _sinks() if 'Razer_Inc_BlackShark' in s[1]]
    if not matches:
        return None
    game = [s for s in matches if 'stereo-game' in s[1] or s[1].endswith('-game')]
    s = (game or matches)[0]
    return s[0], s[1]


def find_headset_sink():
    """Public name-only wrapper around _find_game_sink()."""
    found = _find_game_sink()
    return found[1] if found else None


def _sink_input_ids_on(sink_id):
    ok, out, _ = _pactl('list', 'sink-inputs', 'short')
    if not ok:
        return []
    return [f[0] for f in (l.split('\t') for l in out.splitlines())
            if len(f) >= 2 and f[1] == sink_id]


def enable():
    """Turn THX-style surround on — scoped to the headset's *game* sink
    only, never chat/voice-call audio. Returns (ok, err). Doesn't touch the
    system default sink at all: streams are moved onto the convolver
    explicitly, and its output is pinned (target.object) straight back to
    the game sink, so nothing about chat or any other app's routing
    changes."""
    if not components_installed():
        return False, 'THX components not installed'

    game = _find_game_sink()
    if not game:
        return False, 'headset game audio sink not found (is it connected?)'
    _, game_name = game

    new_conf = _render_conf(game_name)
    try:
        with open(CONF_PATH) as f:
            current = f.read()
    except OSError:
        current = None

    sink_already_live = any(s[1] == SINK_NAME for s in _sinks())
    if current != new_conf or not sink_already_live:
        os.makedirs(os.path.dirname(CONF_PATH), exist_ok=True)
        with open(CONF_PATH, 'w') as f:
            f.write(new_conf)
        r = subprocess.run(['systemctl', '--user', 'restart', 'pipewire', 'pipewire-pulse'],
                            capture_output=True, text=True, timeout=15)
        if r.returncode != 0:
            return False, f'pipewire restart failed: {r.stderr.strip()}'
        if not _wait_for_sink(SINK_NAME):
            return False, 'virtual surround sink did not appear after restart'

    # Re-resolve and sweep for a beat rather than a single snapshot-and-move:
    # a restart invalidates every sink/sink-input id, and separately a
    # stream can still be mid-(re)connect (e.g. a game briefly re-opening
    # its audio device), so one-shot matching can miss it.
    for _ in range(4):
        game = _find_game_sink()
        if game:
            game_id, _ = game
            for sid in _sink_input_ids_on(game_id):
                _pactl('move-sink-input', sid, SINK_NAME)
        time.sleep(0.25)

    return True, None


def disable():
    """Turn THX-style surround off — moves anything currently on the
    convolver back onto the headset's game sink. The filter-chain config is
    left in place — it's idle/no-cost when nothing routes through it, so no
    PipeWire restart is needed to turn off."""
    for _ in range(4):
        virt = next((s for s in _sinks() if s[1] == SINK_NAME), None)
        game = _find_game_sink()
        if virt and game:
            for sid in _sink_input_ids_on(virt[0]):
                _pactl('move-sink-input', sid, game[1])
        time.sleep(0.25)
    return True, None


def _render_conf(target):
    return _CONF_TEMPLATE.replace('__IR_FILE__', IR_FILE).replace('__TARGET__', target)


def _wait_for_sink(name, timeout=3.0, tries=6):
    for _ in range(tries):
        if any(s[1] == name for s in _sinks()):
            return True
        time.sleep(timeout / tries)
    return False
